name: Release daemon
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./daemon
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: daemon/go.mod
          cache-dependency-path: daemon/go.sum
      - name: Install dependencies
        run: go get .
      - name: Run tests
        run: go test ./...
      - name: Build
        run: go build -v -o powerhusky-daemon-linux-amd64 cmd/main.go
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: daemon/powerhusky-daemon-linux-amd64
