name: Test webhook
on:
  push:
    branches: ["main"]

jobs:
  test-webhook:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webhook
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          # Use latest version of Golang for testing
          go-version-file: daemon/go.mod
          cache-dependency-path: webhook/go.sum
      - name: Install dependencies
        run: go get .
      - name: Run tests
        run: go test -v ./...
