name: Test daemon
on:
  push:
    branches: ["main"]

jobs:
  test-daemon:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./daemon
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: daemon/go.mod
          cache-dependency-path: daemon/go.sum
      - name: Install dependencies
        run: go get .
      - name: Run tests
        run: go test ./...
